spring.application.name=PropertyPlatfrorm

jwt.secret=${SECRET_KEY}

spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.datasource.connection

spring.mongodb.uri=${MONGO_URL}
spring.mongodb.database=${MONGO_DB_NAME}


spring.rabbitmq.host=${PROD_RABBIT_MQ_HOST}
spring.rabbitmq.port=${PROD_RABBIT_MQ_PORT}
spring.rabbitmq.username=${PROD_RABBIT_MQ_USER}
spring.rabbitmq.password=${PROD_RABBIT_MQ_PASSWORD}
spring.rabbitmq.virtual-host=${PROD_RABBIT_MQ_VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.listener.direct.acknowledge-mode=manual
spring.rabbitmq.listener.direct.prefetch=1
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=3


spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=disougie
spring.mail.password=disougie
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.data.redis.url=${PROD_REDIS_URL}

imagekit.url=${IMAGEKIT_URL}
imagekit.public.key=${IMAGEKIT_PUBLIC_KEY}
imagekit.private.key=${IMAGEKIT_PRIVATE_KEY}
